Seminario/Controllers/FaesController.cs
using Seminario.Models;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Data;
using ClosedXML.Excel;
using System.IO;
using System.Web.Security;
using Seminario.Models.Seguridad;

namespace Seminario.Controllers
{
    [Authorize]
    public class FaesController : Controller
    {
        private SeminarioContext db = new SeminarioContext();
        public ActionResult Index()
        {
            var user = (UsuarioMembership)Membership.GetUser();
            var logueado = db.Usuarios.Include(c => c.Municipio).FirstOrDefault(c => c.Id == user.Id);
            if (logueado.TipoUsuario != TipoUsuario.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            Filtro filtro = new Filtro()
            {
                Anio = (Anio)DateTime.Now.Year,
                Mes = (Mes)DateTime.Now.Month - 1,
                Dia = 0,
                Hora = 0
            };
            var municipios = db.Municipios.Where(c => c.Comisaria == logueado.Municipio.Comisaria).ToList();
            ViewBag.MunicipioId = new SelectList(municipios, "Id", "Nombre");
            return View(filtro);
        }

        [HttpPost]
        public ActionResult Index(Filtro filtro)
        {
            var user = (UsuarioMembership)Membership.GetUser();
            var logueado = db.Usuarios.Include(c => c.Municipio).FirstOrDefault(c => c.Id == user.Id);
            var municipios = db.Municipios.Where(c => c.Comisaria == logueado.Municipio.Comisaria).ToList();
            if (ModelState.IsValid)
            {
                int dias = DateTime.DaysInMonth((int)filtro.Anio, (int)filtro.Mes + 1);
                if (dias < filtro.Dia)
                {
                    ViewBag.Mensaje = $"El mes solo tiene {dias} dias";
                    ViewBag.MunicipioId = new SelectList(municipios, "Id", "Nombre", filtro.MunicipioId);
                    return View(filtro);
                }

                TempData["nombreCompleto"] = filtro;
                return RedirectToAction("Graficas");
            }

            ViewBag.MunicipioId = new SelectList(municipios, "Id", "Nombre", filtro.MunicipioId);
            return View(filtro);
        }

        public ActionResult Export()
        {
            var user = (UsuarioMembership)Membership.GetUser();
            var logueado = db.Usuarios.Include(c => c.Municipio).FirstOrDefault(c => c.Id == user.Id);
            if (logueado.TipoUsuario != TipoUsuario.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }
            Excel excel = new Excel()
            {
                Anio = (Anio)DateTime.Now.Year,
                Mes = (Mes)DateTime.Now.Month - 1
            };
            var municipios = db.Municipios.Where(c => c.Comisaria == logueado.Municipio.Comisaria).ToList();
            ViewBag.MunicipioId = new SelectList(municipios, "Id", "Nombre");
            return View(excel);
        }

        [HttpPost]
        public ActionResult Export(Excel excel)
        {
            if (ModelState.IsValid)
            {
                List<HechoDelictivo> hechosDelictivos = ListaExport(excel);

                if (hechosDelictivos.Count() > 0)
                {
                    DataTable dtVida = new DataTable("Contra la Vida");
                    DataTable dtPatrimonio = new DataTable("Contra el Patrimonio");
                    dtVida.Columns.AddRange(
                        new DataColumn[10]{
                        new DataColumn("Oficinista"),
                        new DataColumn("Fecha"),
                        new DataColumn("Lugar"),
                        new DataColumn("Dirección"),
                        new DataColumn("Nombre de la Victima"),
                        new DataColumn("Género"),
                        new DataColumn("Edad"),
                        new DataColumn("Delito"),
                        new DataColumn("Causa"),
                        new DataColumn("Observaciones")
                    });

                    dtPatrimonio.Columns.AddRange(
                        new DataColumn[21]{
                        new DataColumn("Oficinista"),
                        new DataColumn("Fecha"),
                        new DataColumn("Lugar"),
                        new DataColumn("Dirección"),
                        new DataColumn("Nombre de la Victima"),
                        new DataColumn("Género"),
                        new DataColumn("Edad"),
                        new DataColumn("Delito"),
                        new DataColumn("Tipo"),
                        new DataColumn("Placas"),
                        new DataColumn("Marca"),
                        new DataColumn("Color"),
                        new DataColumn("Modelo"),
                        new DataColumn("Motor"),
                        new DataColumn("Chasis"),
                        new DataColumn("Móvil"),
                        new DataColumn("Registro"),
                        new DataColumn("Calibre"),
                        new DataColumn("Oficio"),
                        new DataColumn("Denunciante"),
                        new DataColumn("Observaciones")
                        });
                    if (hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraLaVida).Count() > 0)
                    {
                        foreach (var item in hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraLaVida))
                        {
                            dtVida.Rows.Add(
                               $"{item.Usuario.Nombre} {item.Usuario.Apellido}",
                               item.Fecha,
                               item.Lugar.Nombre,
                               item.Direccion,
                               item.NombreVictima,
                               item.Genero,
                               item.Edad,
                               item.Delito.Nombre,
                               item.Causa,
                               item.Observaciones
                                );
                        }
                    }
                    if (hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraElPatrimonio).Count() > 0)
                    {
                        foreach (var item in hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraElPatrimonio))
                        {
                            dtPatrimonio.Rows.Add(
                               $"{item.Usuario.Nombre} {item.Usuario.Apellido}",
                               item.Fecha,
                               item.Lugar.Nombre,
                               item.Direccion,
                               item.NombreVictima,
                               item.Genero,
                               item.Edad,
                               item.Delito.Nombre,
                               item.Tipo,
                               item.Placas,
                               item.Marca,
                               item.Color,
                               item.Modelo,
                               item.Motor,
                               item.Chasis,
                               item.Movil,
                               item.Registro,
                               item.Calibre,
                               item.Oficio,
                               item.Denunciante,
                               item.Observaciones
                                );
                        }
                    }

                    using (XLWorkbook wb = new XLWorkbook())
                    {
                        if (hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraLaVida).Count() > 0)
                        {
                            wb.Worksheets.Add(dtVida);
                        }
                        if (hechosDelictivos.Where(c => c.Delito.TipoDelito == TipoDelito.ContraElPatrimonio).Count() > 0)
                        {
                            wb.Worksheets.Add(dtPatrimonio);
                        }
                        using (MemoryStream stream = new MemoryStream())
                        {
                            ViewBag.Mensaje = "";
                            wb.SaveAs(stream);
                            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"HechosDelictivos{hechosDelictivos[0].Lugar.Municipio.Nombre}{excel.Mes}{excel.Anio}.xlsx");
                        }
                    }

                }
            }
            ViewBag.Mensaje = "El mes no contiene datos que exportar.";
            var user = (UsuarioMembership)Membership.GetUser();
            var logueado = db.Usuarios.Include(c => c.Municipio).FirstOrDefault(c => c.Id == user.Id);
            var municipios = db.Municipios.Where(c => c.Comisaria == logueado.Municipio.Comisaria).ToList();
            ViewBag.MunicipioId = new SelectList(municipios, "Id", "Nombre", excel.MunicipioId);
            return View(excel);
        }

        public List<HechoDelictivo> ListaExport(Excel excel)
        {
            return db.HechosDelictivos
                    .Include(c => c.Usuario)
                    .Include(c => c.Lugar)
                    .Include(c => c.Lugar.Municipio)
                    .Include(c => c.Delito)
                    .Where(c => c.Lugar.Municipio.Id == excel.MunicipioId
                    && c.Fecha.Year == (int)excel.Anio
                    && c.Fecha.Month == (int)excel.Mes + 1)
                    .ToList();
        }

        public ActionResult Graficas()
        {
            Filtro filtro = TempData["nombreCompleto"] as Filtro;

            if (filtro == null)
            {
                return RedirectToAction("Index");
            }

Seminario/Controllers/LoginController.cs
using Seminario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Seminario.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            using (var context = new SeminarioContext())
            {
                if (context.Municipios.ToList().Count == 0)
                {
                    Municipio municipio = new Municipio()
                    {
                        Nombre = "Salama",
                        Comisaria = Comisaria.C52_1
                    };
                    context.Municipios.Add(municipio);
                    Usuario usuario = new Usuario()
                    {
                        Nombre = "ADMIN",
                        Apellido = "ISTRADOR",
                        Telefono = 00000000,
                        Correo = "admin@admin.com",
                        User = "admin",
                        Password = "salama2018",
                        MunicipioId = municipio.Id,
                        TipoUsuario = TipoUsuario.Administrador,
                        Estado = EstadoUsuario.Activo,
                    };
                    context.Usuarios.Add(usuario);
                    context.SaveChanges();
                }
                if (context.Usuarios.Where(c => c.TipoUsuario == TipoUsuario.Administrador).ToList().Count == 0)
                {
                    Municipio municipio = context.Municipios.FirstOrDefault();
                    Usuario usuario = new Usuario()
                    {
                        Nombre = "ADMIN",
                        Apellido = "ISTRADOR",
                        Telefono = 00000000,
                        Correo = "admin@admin.com",
                        User = "admin",
                        Password = "salama2018",
                        MunicipioId = municipio.Id,
                        TipoUsuario = TipoUsuario.Administrador,
                        Estado = EstadoUsuario.Activo,
                    };
                    context.Usuarios.Add(usuario);
                    context.SaveChanges();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(UsuarioLogin usuario)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(usuario.User, usuario.Password))
                {
                    FormsAuthentication.RedirectFromLoginPage(usuario.User, false);
                    return null;
                }
            }
            ViewBag.Mensaje = "Usuario o Contraseña Incorrecta";
            return View(usuario);
        }

        public ActionResult Logoff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

Seminario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EPO</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("head_scripts", required: false)

    <style>
        .navbar-inverse {
            background-color: navy;
            border-color: navy;
        }

            .navbar-inverse .navbar-brand,
            .navbar-inverse .navbar-brand {
                color: white;
                background-color: transparent;
            }

            .navbar-inverse .navbar-nav > li > a,
            .navbar-inverse .navbar-nav > li > a {
                color: white;
                background-color: transparent;
            }

        footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 50px;
            background-color: navy;
            color: white;
            text-align: center;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a href="@Url.Action("Index", "Home")" title="List View" class="links">
                    <img src="~/images/pnc.png" width="60" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Municipios", "Index", "Municipios")  </li>
                        <li>@Html.ActionLink("Usuarios", "Index", "Usuarios")  </li>
                        <li>@Html.ActionLink("Lugares", "Index", "Lugares")  </li>
                        <li>@Html.ActionLink("Delitos", "Index", "Delitos")  </li>
                        <li>@Html.ActionLink("Hechos Delictivos", "Index", "HechosDelictivos")  </li>
                        <li>@Html.ActionLink("FAES", "Index", "Faes")  </li>
                    </ul>


                    <ul class="nav navbar-nav navbar-right">
                        <li><a><i class="glyphicon glyphicon-user"></i>&nbsp;@ViewBag.Mensaje</a></li>
                        <li>
                            <a href="@Url.Action("Logoff", "Login")" title="List View" class="links">
                                <i class="glyphicon glyphicon-log-out"></i>&nbsp;Salir
                            </a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <br />
        <p>&copy; Seminaristas UMG @DateTime.Now.Year</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>